name: 'TODO: Run <linter-name> with reviewdog'
description: 'TODO: 🐶 Run <linter-name> with reviewdog on pull requests to improve code review experience.'
author: 'TODO: <your-name>'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  debride_version:
    description: 'Debride version'
  debride_flags:
    description: 'Debride flags. (debride <debride_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'debride'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-check,github-pr-review].'
    default: 'github-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.14.1
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_DEBRIDE_VERSION: ${{ inputs.debride_version }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}

branding:
  icon: 'check'
  color: 'blue'
